//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioProducto
    {
        public int IdUsuarioProducto { get; set; }
        public int IdUsuario { get; set; }
        public int IdProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
    
        public virtual ProductoPrueba ProductoPrueba { get; set; }
        public virtual UsuarioPrueba UsuarioPrueba { get; set; }
    }
}
